"""Changed the Vector dimension according to gemini model

Revision ID: 22d32d5b3838
Revises: ad8026c157ee
Create Date: 2026-05-10 18:21:43.167393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "22d32d5b3838"
down_revision: Union[str, None] = "ad8026c157ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=Vector(dim=1536),
        type_=Vector(dim=768),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=Vector(dim=768),
        type_=Vector(dim=1536),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
