"""Changed the Vector dimension to 3072 according to gemini model

Revision ID: c325e2b035fe
Revises: 22d32d5b3838
Create Date: 2026-05-10 18:59:20.817562

"""

from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c325e2b035fe"
down_revision: Union[str, None] = "22d32d5b3838"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=Vector(dim=768),
        type_=Vector(dim=3072),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=Vector(dim=3072),
        type_=Vector(dim=768),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
