"""added name column in chat_session table

Revision ID: f114fb1c8252
Revises: c325e2b035fe
Create Date: 2026-05-16 22:44:52.100141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f114fb1c8252'
down_revision: Union[str, None] = 'c325e2b035fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'name')
    # ### end Alembic commands ###
